#!/usr/bin/env python3
'''Python setup.py.'''
# Copyright 2008 Dan Smith <dsmith@danplanet.com>
# review 2015-2020 Maurizio Andreotti  <iz2lxi@yahoo.it>
# Copyright 2022 John. E. Malmberg - Python3 Conversion
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

from __future__ import absolute_import
from __future__ import print_function

from os import system
from os.path import dirname, exists, join
from glob import glob
from setuptools import setup

from d_rats.version import DRATS_VERSION

def default_build():
    '''Default Build.'''

    print('Creating d_rats/setup_version.py')
    with open('d_rats/setup_version.py', 'w') as version_file:
        version_file.write("'''Setup Version.'''\n")
        version_file.write("# This file generated by python -m build\n")
        version_file.write('SETUP_VERSION = "%s"\n' % DRATS_VERSION)
        print('Created d_rats/setup_version.py')

    data_files = []
    system("make -C libexec clean")
    system("make -C libexec")
    bin_lzhuf = join('libexec', 'lzhuf')
    if not exists(bin_lzhuf):
        bin_lzhuf += ".exe"
    data_files.append(('/usr/share/d-rats/libexec', [bin_lzhuf]))

    section_files = glob("share/*.desktop")
    data_files.append(('share/applications', section_files))

    data_files.append(('share/icons', ['share/d-rats2.xpm']))

    section_files = glob("forms/*.x?l")
    data_files.append(('share/d-rats/forms', section_files))

    section_files = glob("images/*")
    section_files.append("d-rats2.ico")
    section_files.append("share/d-rats2.xpm")
    data_files.append(('share/d-rats/images', section_files))

    ui_files = ['ui/addport.glade', 'ui/mainwindow.glade']

    data_files.append(('share/d-rats/ui', ui_files))

    system('towncrier build --yes')

    section_files = ['COPYING']
    doc_srcs = ['changelog', 'NEWS.rst']
    for file_name in doc_srcs:
        file_gz = file_name + ".gz"
        system("gzip -c %s > %s" % (file_name, file_gz))
        section_files.append(file_gz)
    data_files.append(('share/doc/d-rats/', section_files))

    section_files = []
    man_src_files = glob("share/*.1")
    for file_name in man_src_files:
        file_gz = file_name + ".gz"
        system("gzip -c %s > %s" % (file_name, file_gz))
        section_files.append(file_gz)
    data_files.append(('share/man/man1', section_files))

    locale_po_files = glob("locale/*/LC_MESSAGES/D-RATS.po")
    for file_name in locale_po_files:
        locale_dir = dirname(file_name)
        command = "msgfmt -o %s/D-RATS.mo %s/D-RATS" % (locale_dir, locale_dir)
        system(command)

    locale_mo_files = glob("locale/*/LC_MESSAGES/D-RATS.mo")
    mo_prefix = 'share/'
    for file_name in locale_mo_files:
        data_files.append((mo_prefix + dirname(file_name), [file_name]))

    setup(scripts=['d-rats.py', 'd-rats_repeater.py'],
          data_files=data_files)

default_build()
