#
# Makefile foe OpenWatcom nmake
#
CC=wcc386
CFLAGS=-w4 -e25 -zq -od -d2 -6r -bt=nt -fo=.obj -mf -DLZHUF
LD=link386
LDFLAGS=-opt:ref -release
RM=del
SOURCES=main.c lzhuf.c
OBJECTS=$(SOURCES:.c=.obj)
EXECUTABLE=LZHUF_1.EXE

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(LD) $(LDFLAGS) -out:$(EXECUTABLE) $(OBJECTS)

.c.obj:
	$(CC) $(CFLAGS) $<

clean:
	$(RM) $(EXECUTABLE) $(OBJECTS) $(EXECUTABLE) 
