#!/bin/bash
# Start/stop the d-rats_repeater.
#
### BEGIN INIT INFO
# Provides:          d-rats_repeater
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: D-Rats Repater
# Description:       D-Rats Repater is a repeater for D-Rats
### END INIT INFO

# Service Config
DAEMON=d-rats_repeater.py
DAEMON_PATH=/usr/local/bin/
DAEMON_OPTS="--console &"
#
# To use specific config and log locations edit and use options below
# Don't forget the '&' at the end of the options line, otherwise
# the repeater software will run in foreground.
#
#DAEMON_OPTS="--console --config=/opt/d-rats/etc --log=/opt/d-rats/var/log &"

PGREP="/bin/pidof -x"
KILL=/bin/kill
SLEEP=/bin/sleep
USER=root
GROUP=root

# Pre-flight checks...
test -x $DAEMON_PATH$DAEMON || exit 1

case "$1" in
        start)
                if [ `$PGREP $DAEMON` ]; then
                        echo -e "$DAEMON is already running as PID "`$PGREP $DAEMON`
                        exit 1;
                else
                        runuser -l $USER -c "$DAEMON_PATH$DAEMON $DAEMON_OPTS"
                        echo -e "$DAEMON started as PID "`$PGREP $DAEMON`
                        exit 0;
                fi
                ;;
        stop)
                if [ `$PGREP $DAEMON` ]; then
                        echo -e "Killing $DAEMON PID "`$PGREP $DAEMON`
                        $KILL `$PGREP $DAEMON`
                        exit 0;
                else
                        echo -e "$DAEMON is not running"
                        exit 1;
                fi
                ;;

        restart)
                if [ `$PGREP $DAEMON` ]; then
                        echo -e "Killing $DAEMON PID "`$PGREP $DAEMON`
                        $KILL `$PGREP $DAEMON`
                        $SLEEP 3
                        runuser -l $USER -c "$DAEMON_PATH$DAEMON $DAEMON_OPTS"
                        echo -e "$DAEMON re-started as PID "`$PGREP $DAEMON`
                        exit 0;
                else
                        echo -e "$DAEMON is not running"
                        runuser -l $USER -c "$DAEMON_PATH$DAEMON $DAEMON_OPTS"
                        echo -e "$DAEMON started as PID "`$PGREP $DAEMON`
                        exit 0;
                fi
                ;;

        status)
                if [ `$PGREP $DAEMON` ]; then
                        echo -e "$DAEMON is running as PID "`$PGREP $DAEMON`
                else
                        echo -e "$DAEMON is not running"
                fi
                ;;

        *)
                echo $"Usage: $0 {start|stop|restart|status}"
                exit 1
esac

