---
name: ShellCheck

# Always run on Pull Requests
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  pylint:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install core packages
        run: |
          ./tests/install_shellcheck_ubuntu.sh
      - name: Pull via git
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
      - name: Show git diff
        run: |
           git diff --name-only ${{ github.event.pull_request.base.sha }}
      - name: Do the ShellCheck
        run: |
          base_sha="${{ github.event.pull_request.base.sha }}"
          changed="$(git diff --name-only $base_sha)"
          export CHANGED_FILES="$changed"
          ./tests/pre-commit_d/shellcheck_check.sh
