---
name: Yamllint

# Always run on Pull Requests
on:  # yamllint disable-line rule:truthy
  - pull_request

jobs:
  yamllint:
    name: Run Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: false
